### ISSUE TITLE
Auto skin selection

### ISSUE THREAD

**Issue by vcro** [Mokhet/MFF-roster-tracker#39]
Hello, it's not a issue but a impovement can you put auto skin selection : i explain , when you select an skin , it doesn't activate it (automatically) on the uniform upgrade page( it doen't put the skin on normal for the skin upgrad).

Can you put this feature plz ?

thanks your for your work it's awesome 

PS: sorry for ma bad english , it's not my native laguage

best regards. VCRO

**Comment by Mokhet** [comment]
Hello, sorry but I do not understand. Currently, when you set an uniform as the selected one, the pictures are automatically synchronised and you go back to the character this selected uniform is selected.

Can you give me an example please ? It would help me understand the issue and let me see how I can implement it.

If you happen to speak French, it would help since I am french.

**Comment by vcro** [comment]
bonjour,

c'est beaucoup plus simple en français :)
en gros quand on choisi l'uniforme d'un personnage ca change bien l'affichage mais ca ne met pas qu'on la débloqué dans la page des amélioration des uniformes: 
Pour faire plus simple quand on sélectionne l'uniforme que ça met le rank automatiquement en normal.

Super boulot en tout cas :D

Cordialement.VCRO

**Comment by Mokhet** [comment]
Ahh en français c'est plus simple :)

Je n'y avais pas pensé, mais effectivement, très bonne idée et plutôt simple à implémenter.

M'en occupe.

**Comment by Mokhet** [comment]
C'est fait, et c'est en ligne.
